[deps]
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SDDP = "f4570300-c277-11e8-125c-4912f86ce65d"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"

[compat]
HiGHS = "1"
Plots = "1"
SDDP = "1"
